# Base configs
baseurl: ""

# UI configs
title: "Milin Patel"
author: "Milin Patel"
about: "Valar Morghulis"
social_urls:
  facebook: ""
  twitter: "https://www.twitter.com/milinpatel13298"
  instagram: "https://www.instagram.com/milinpatel13298"
