# Base configs
baseurl: ""

# UI configs
title: "Milin Patel"
author: "Milin Patel"
about: ""
social_urls:
  facebook: "https://www.facebook.com/milin.patel3"
  twitter: "https://www.twitter.com/milinpatel13298"
  instagram: "https://www.instagram.com/milinpatel13298"
